language: android
env:
  - JAVA_OPTS="-Xms512m -Xmx512m -XX:MaxPermSize=256m"
android:
  components:
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-19
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17
install:
  - sudo curl -o /usr/bin/sbt https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt
  - sudo chmod +x /usr/bin/sbt
script:
  - sbt update
  - sbt android:package-debug
  - sbt doc
